# Default values for django app
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    uwsgi: ""
    nginx: ""
    cloudsqlProxy:
      project: apsl-hosting-pre
      name: apsl-hosting-pre
      zone: europe-west1
      port: "5432"
      filename: cloudsql-authorization.json
  cloudsqlProxy:
    tag: "1.11"
    ports:
     - name: postgres
       containerPort: 5432
  dataSecrets:
  dataConfigMap:


nginx-uwsgi:
  secrets:
    secretKey: ""
    passwordDB: ""
    sentryDSN: ""


crons:
  enabled: true
  secrets:
    enabled: false
  service:
    enabled: false
  configMap:
    enabled: false
  crons:
    enabled: true
  deployment:
    probes:
      liveness:
        enabled: false


celery:
  enabled: false
  secrets:
    enabled: false
  service:
    enabled: false
  configMap:
    enabled: false
  celery:
    enabled: true
  deployment:
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false


rq:
  enabled: false
  secrets:
    enabled: false
  service:
    enabled: false
  configMap:
    enabled: false
  djangoRQ:
    enabled: true
  deployment:
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false

# BackendHost takes release name as a prefix: {{ RELEASE_NAME-backendHost }}
varnish:
  enabled: true
  backendHost: ""
