{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: {{ .Values.secrets.type }}
data:
  django.secretKey: {{ randAlphaNum 10 | b64enc | quote }}
  django.sentryDSN: {{ .Values.secrets.sentryDSN | toString | b64enc }}

{{- if .Values.global.dataSecrets }}
{{- range $secret := .Values.global.dataSecrets }}
  {{ $secret.key }}: {{ $secret.value | b64enc }}
{{- end }}
{{- end }}

{{- end }}
